version: '2'
services:
  push-notifier:
    build: ./push-notifier/
    ports:
      - "3006:3006"
    environment:
      - INCOMING_PUSH_PORT=3006
    volumes:
      - ./push-notifier/src:/opt/push-notifier

  event-api:
    build: ./event-api/
    ports:
      - "3007:3007"
    environment:
      - EVENT_API_PORT=3007
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdfasdf
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_HOST=db
    links:
      - push-notifier
    volumes:
      - ./event-api/src:/opt/event-api
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local